static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: { address: 0.0.0.0, port_value: 10000 }
      filter_chains:
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext 
            common_tls_context:
              tls_certificates:
                - certificate_chain: { filename: /ca/LI-SERVER-TLS-CERT }
                  private_key: { filename: /ca/LI-SERVER-TLS-KEY }

      filter_chains:             
        - filters:         
          - name: envoy.filters.network.tcp_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              stat_prefix: destination
              cluster: cluster_0
                
  clusters:
    - name: cluster_0
      connect_timeout: 30s
      load_assignment:
        cluster_name: cluster_0
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address: { address: 127.0.0.1, port_value: 1447 } 
      transport_socket:
        name: envoy.transport_sockets.cluster.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext 
          common_tls_context:
            tls_certificates:
              - certificate_chain: { filename: /ca/LI-CLIENT-TLS-CERT }
                private_key: { filename: /ca/LI-CLIENT-TLS-KEY }
            validation_context:
              trusted_ca: { filename : /ca/LI-CA-CERT }
