receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:12345

exporters:
  prometheus:
    endpoint: '0.0.0.0:9090'

processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
      processors: [batch]