apiVersion: apps/v1
kind: Deployment
metadata:
  name: http2-server
  labels:
    app: http2-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http2-server
  template:
    metadata:
      labels:
        app: http2-server
    spec:
      containers:
      - name: http2
        image: http2:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
