// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: hello.proto

#include "hello.pb.h"
#include "hello.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace hello {

static const char* Example_method_names[] = {
  "/hello.Example/ExampleRPC",
};

std::unique_ptr< Example::Stub> Example::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Example::Stub> stub(new Example::Stub(channel, options));
  return stub;
}

Example::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ExampleRPC_(Example_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Example::Stub::ExampleRPC(::grpc::ClientContext* context, const ::hello::Request& request, ::hello::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hello::Request, ::hello::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ExampleRPC_, context, request, response);
}

void Example::Stub::async::ExampleRPC(::grpc::ClientContext* context, const ::hello::Request* request, ::hello::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hello::Request, ::hello::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExampleRPC_, context, request, response, std::move(f));
}

void Example::Stub::async::ExampleRPC(::grpc::ClientContext* context, const ::hello::Request* request, ::hello::Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExampleRPC_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hello::Response>* Example::Stub::PrepareAsyncExampleRPCRaw(::grpc::ClientContext* context, const ::hello::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hello::Response, ::hello::Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ExampleRPC_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hello::Response>* Example::Stub::AsyncExampleRPCRaw(::grpc::ClientContext* context, const ::hello::Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncExampleRPCRaw(context, request, cq);
  result->StartCall();
  return result;
}

Example::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Example_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Example::Service, ::hello::Request, ::hello::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Example::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hello::Request* req,
             ::hello::Response* resp) {
               return service->ExampleRPC(ctx, req, resp);
             }, this)));
}

Example::Service::~Service() {
}

::grpc::Status Example::Service::ExampleRPC(::grpc::ServerContext* context, const ::hello::Request* request, ::hello::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace hello

