// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: hello.proto
#ifndef GRPC_hello_2eproto__INCLUDED
#define GRPC_hello_2eproto__INCLUDED

#include "hello.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace hello {

class Example final {
 public:
  static constexpr char const* service_full_name() {
    return "hello.Example";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ExampleRPC(::grpc::ClientContext* context, const ::hello::Request& request, ::hello::Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hello::Response>> AsyncExampleRPC(::grpc::ClientContext* context, const ::hello::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hello::Response>>(AsyncExampleRPCRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hello::Response>> PrepareAsyncExampleRPC(::grpc::ClientContext* context, const ::hello::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hello::Response>>(PrepareAsyncExampleRPCRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void ExampleRPC(::grpc::ClientContext* context, const ::hello::Request* request, ::hello::Response* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ExampleRPC(::grpc::ClientContext* context, const ::hello::Request* request, ::hello::Response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::hello::Response>* AsyncExampleRPCRaw(::grpc::ClientContext* context, const ::hello::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::hello::Response>* PrepareAsyncExampleRPCRaw(::grpc::ClientContext* context, const ::hello::Request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ExampleRPC(::grpc::ClientContext* context, const ::hello::Request& request, ::hello::Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hello::Response>> AsyncExampleRPC(::grpc::ClientContext* context, const ::hello::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hello::Response>>(AsyncExampleRPCRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hello::Response>> PrepareAsyncExampleRPC(::grpc::ClientContext* context, const ::hello::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hello::Response>>(PrepareAsyncExampleRPCRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ExampleRPC(::grpc::ClientContext* context, const ::hello::Request* request, ::hello::Response* response, std::function<void(::grpc::Status)>) override;
      void ExampleRPC(::grpc::ClientContext* context, const ::hello::Request* request, ::hello::Response* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::hello::Response>* AsyncExampleRPCRaw(::grpc::ClientContext* context, const ::hello::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::hello::Response>* PrepareAsyncExampleRPCRaw(::grpc::ClientContext* context, const ::hello::Request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ExampleRPC_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ExampleRPC(::grpc::ServerContext* context, const ::hello::Request* request, ::hello::Response* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ExampleRPC : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ExampleRPC() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ExampleRPC() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExampleRPC(::grpc::ServerContext* /*context*/, const ::hello::Request* /*request*/, ::hello::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExampleRPC(::grpc::ServerContext* context, ::hello::Request* request, ::grpc::ServerAsyncResponseWriter< ::hello::Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ExampleRPC<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ExampleRPC : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ExampleRPC() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::hello::Request, ::hello::Response>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::hello::Request* request, ::hello::Response* response) { return this->ExampleRPC(context, request, response); }));}
    void SetMessageAllocatorFor_ExampleRPC(
        ::grpc::MessageAllocator< ::hello::Request, ::hello::Response>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::hello::Request, ::hello::Response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ExampleRPC() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExampleRPC(::grpc::ServerContext* /*context*/, const ::hello::Request* /*request*/, ::hello::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ExampleRPC(
      ::grpc::CallbackServerContext* /*context*/, const ::hello::Request* /*request*/, ::hello::Response* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ExampleRPC<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ExampleRPC : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ExampleRPC() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ExampleRPC() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExampleRPC(::grpc::ServerContext* /*context*/, const ::hello::Request* /*request*/, ::hello::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ExampleRPC : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ExampleRPC() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ExampleRPC() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExampleRPC(::grpc::ServerContext* /*context*/, const ::hello::Request* /*request*/, ::hello::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExampleRPC(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ExampleRPC : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ExampleRPC() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ExampleRPC(context, request, response); }));
    }
    ~WithRawCallbackMethod_ExampleRPC() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExampleRPC(::grpc::ServerContext* /*context*/, const ::hello::Request* /*request*/, ::hello::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ExampleRPC(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ExampleRPC : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ExampleRPC() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::hello::Request, ::hello::Response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::hello::Request, ::hello::Response>* streamer) {
                       return this->StreamedExampleRPC(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ExampleRPC() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ExampleRPC(::grpc::ServerContext* /*context*/, const ::hello::Request* /*request*/, ::hello::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedExampleRPC(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::hello::Request,::hello::Response>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ExampleRPC<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ExampleRPC<Service > StreamedService;
};

}  // namespace hello


#endif  // GRPC_hello_2eproto__INCLUDED
