# Use the official Redis image from Docker Hub
FROM redis:latest

# Expose Redis port
EXPOSE 6379

# Optional: Set a default command (not strictly necessary, as redis:latest does this)
#CMD ["redis-server"]
